tipi.lo: /home/martin/project/c/phpsrc/ext/tipi/tipi.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/martin/project/c/phpsrc/ext/tipi $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/martin/project/c/phpsrc/ext/tipi/tipi.c -o tipi.lo 
$(phplibdir)/tipi.la: ./tipi.la
	$(LIBTOOL) --mode=install cp ./tipi.la $(phplibdir)

./tipi.la: $(shared_objects_tipi) $(TIPI_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_tipi) $(TIPI_SHARED_LIBADD)

